name: Deploy website
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Restore dependencies
        run: npm ci
      - name: Deploy to Vercel
        run: npm run deploy -- --token ${{ secrets.VERCEL_TOKEN }}
